[project]
name = "stag"
version = "0.1.7"
authors = [
    {name = "Manfred Stoiber", email = "manfred.stoiber@gmail.com"}
]
description = "STag - A Stable, Occlusion-Resistant Fiducial Marker System"
requires-python = ">=3.7"
readme = "README.md"
dependencies = [
    "numpy"
]

[build-system]
requires = [
    "scikit_build_core>=0.3.3",
    "pybind11",
    "oldest-supported-numpy",
    "requests",
    "urllib3<2" # requests does not work with urllib>2 on python 3.7, since openssl1.1.1+ is not available
]
build-backend = "scikit_build_core.build"

#[tool.setuptools]
#license-files = [
#    "submodules/*/LICENSE",
#    "LICENSE"
#]

[tool.scikit-build]
wheel.expand-macos-universal-tags = true

#[tool.setuptools.package-data]
#"stag" = ["libopencv_imgproc*", "libopencv_core*"]
